const areas = [
    {
        area1Titulo: "DERECHO PENAL",
        area1Item1Titulo: "Pasar por un proceso penal puede resultar tedioso y desgastante, en OSAP abogados litigantes contamos con una estrategia técnica legal adaptada a tus necesidades para cada una de las etapas del proceso penal.        ",
        area1Item1subTitulo: "",
        area1Item2Titulo: "En un mundo globalizado, las redes sociales se han convertido en un eficiente medio para cometer estafas, si eres una víctima, contáctanos y nosotros nos encargamos de evaluar tu caso e iniciar las acciones legales que se ajusten a tus intereses.        ",
        area1Item2subTitulo: "",
    },
    {
        area1Titulo: "ACCIDENTES DE TRÁNSITO",
        area1Item1Titulo: "¿Sufriste un accidente de tránsito y requieres asesoría legal?",
        area1Item1subTitulo: "El alto flujo vehicular que existe en las principales provincias del país, incrementa sustancialmente las probabilidades de que te veas envuelto en un accidente de tránsito. En OSAP abogados litigantes, contamos con profesionales capacitados en la materia que pondrán a tu disposición sus conocimientos, a fin de evitar una disminución de puntos en tu licencia de conducir y demás sanciones tipificadas en el COIP.",
        area1Item2Titulo: "¿Tienes multas de tránsito por pagar?",
        area1Item2subTitulo: "Consúltanos, podrían estar prescritas. Evita trabas al momento de matricular tu vehículo y acude a profesionales probos a fin de que te ayuden a impugnar de manera eficaz tus citaciones de tránsito.",  
    },
    {
        area1Titulo: "VIOLENCIA INTRAFAMILIAR",
        area1Item1Titulo: "¿Sabías que las agresiones verbales constituyen violencia psicológica?        ",
        area1Item1subTitulo: "Las frases o palabras que denigran a la mujer o la hacen sentir inferior, que no sirve, que está en segundo o tercer orden, las amenazas, entre otras, son ejemplos de violencia psicológica. Si eres una víctima, no dudes en contactarnos, en OSAP abogados litigantes contamos con profesionales expertos en la materia. Contáctanos, te brindaremos la asesoría legal que necesitas.",

    },
    {
        area1Titulo: "FAMILIA, NIÑEZ Y ADOLESCENCIA        ",
        area1Item1Titulo: "¿Quieres divorciarte?",
        area1Item1subTitulo: "Si quieres dar por terminado tu relación marital, en OSAP abogados litigantes ponemos a tu disposición a profesionales capacitados para el efecto. Somos especialistas en aminorar el tiempo de divorcio, consiguiendo que éste sea lo menos traumático y tedioso posible. ",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },
    {
        area1Titulo: "DERECHO SOCIETARIO        ",
        area1Item1Titulo: "¿Quieres constituir una compañía?",
        area1Item1subTitulo: "El impulso económico que promueve el Estado ecuatoriano, ha provocado que varias personas opten por poner en marcha un emprendimiento. En OSAP abogados litigantes te brindamos una asesoría societaria integral que se adapte al monto de tu inversión y actividad comercial, optimizando tus recursos.",
        area1Item2Titulo: "¿Ya cuentas con una compañía, pero ¿no cuentas con una carpeta societaria que avale la actividad comercial de tu empresa durante su existencia legal?",
        area1Item2subTitulo: "Si deseas que tu empresa goce de buena salud societaria, es necesario que te asesores con un equipo de profesionales que te eviten sanciones por las entidades de control, en OSAP abogados litigantes contamos con abogados prestos a brindarte una consultoría integral.  ",  
    },
    {
        area1Titulo: "DERECHO DEL CONSUMIDOR        ",
        area1Item1Titulo: "¿Has sufrido algún caso de abuso contra el consumidor?",
        area1Item1subTitulo: "El amplio catálogo de productos y servicios que se ofertan en nuestro país, ha provocado que con mayor frecuencia se propague la violación de los derechos del consumidor. Si eres un consumidor insatisfecho, haz valer tus derechos con un equipo de profesionales que se encarguen de manera eficaz por hacer respetar los mismos.  ",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },
    {
        area1Titulo: "MIGRACIÓN Y EXTRANJERÍA        ",
        area1Item1Titulo: "¿Eres extranjero y ¿quieres obtener visa ecuatoriana?",
        area1Item1subTitulo: "Nosotros te ayudamos a regular tu estatus migratorio. La regularización del estatus migratorio es un requisito vital para obtener mejores oportunidades laborales y académicas. Si vives en Ecuador o planeas hacerlo, comunícate con nosotros, nuestros abogados ponen a tu disposición sus altos estándares de eficiencia que agilizaran la obtención de un estatus migratorio favorable a tus necesidades.",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },
    {
        area1Titulo: "ARBITRAJE Y MÉTODOS ALTERNATIVOS DE SOLUCIÓN DE CONFLICTOS        ",
        area1Item1Titulo: "¿Te invitaron a reunión en un Centro de Mediación o te demandaron ante algún Centro de Arbitraje?",
        area1Item1subTitulo: "Tú requieres asesorarte previamente con un abogado, consúltanos. En la actualidad, la mediación y el arbitraje son métodos alternativos de solución de conflictos distintos a los tradicionales, en el cual los usuarios se benefician de un proceso breve y sencillo. OSAP abogados litigantes se caracteriza por manejar altos estándares de calidad que provocan que el desempeño a lo largo de la sustanciación de un proceso de arbitraje o mediación sea óptimo, obteniendo resultados favorables.",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },
    {
        area1Titulo: "DERECHO DE COMPETENCIA        ",
        area1Item1Titulo: "¿Estás pensando en generar poder de mercado dentro de tu giro de negocio, a través, de la adquisición de otro operador económico que incremente tu volumen de utilidad?",
        area1Item1subTitulo: "Nosotros te ayudamos con el proceso de fusión respectivo. Muchos operadores económicos debido a su desconocimiento, incurren en procesos de fusión con uno o más competidores sin avisar previamente de dicha operación a la entidad reguladora, teniendo que afrontar a futuro el pago de elevadas sanciones pecuniarias que se resuelven a través de arduos procesos administrativos sancionadores. En OSAP ABOGADOS LITIGANTES, contamos con el equipo de profesionales calificado para asesorarte al respecto, evitando que seas sancionado por falta de notificación a Autoridad competente de proceso de fusión entre operadores económicos.",
        area1Item2Titulo: "¿Los productos o servicios ofertados por tu compañía han sido víctima de actos de denigración, comparación o confusión por parte de tu competidor?",
        area1Item2subTitulo: "Nosotros te brindamos asesoría. El Estado ecuatoriano promueve la libre competencia dentro del territorio nacional, lo cual conlleva a que todos los operadores económicos no incurran en prácticas anticompetitivas que representen una ventaja sustancial sobre sus competidores en el mercado relevante en el que compiten; siendo usual, que los actos de denigración, comparación o confusión, sean estrategias de competencia desleal; comunes, entre varios competidores. Si tu operador económico se ha visto afectado por estas u otras prácticas anticompetitivas que generan desventajas en el mercado, denúncialo. En OSAP ABOGADOS LITIGANTES contamos con abogados que conocen con suficiencia el proceso a seguir acorde a la práctica anticompetitiva que esté afectando el mercado relevante en el que se desempeña tu compañía, consiguiendo óptimos resultados a lo largo de la sustanciación del expediente administrativo sancionador.",  
    },
    {
        area1Titulo: "DERECHO CONSTITUCIONAL        ",
        area1Item1Titulo: "¿Una persona cercana a ti se encuentra privada de la libertad de forma ilegal?",
        area1Item1subTitulo: "Contáctanos. La situación de inestabilidad política, económica y social que vive nuestro país en la actualidad, ha generado que varios sectores de la ciudadanía salgan a protestar por sus derechos, siendo varios de ellos, víctimas de aprensiones ilegales. En OSAP ABOGADOS LITIGANTES, nuestros profesionales pueden ayudarte a plantear el Habeas Corpus, acción constitucional encargada de rest",
        area1Item2Titulo: "¿Solicitaste el acceso a información pública y la institución accionante te negó el acceso a la misma?",
        area1Item2subTitulo: "Nosotros podemos ayudarte. Con habitualidad, muchos ciudadanos se han visto privados de acceder a documentos que están en poder del Estado, siendo esta información de carácter público, viéndose vulnerados tus derechos constitucionales. En OSAP ABOGADOS LITIGANTES, ponemos tu disposición nuestros profesionales que te asesorarán integralmente en busca de que tus derechos se vean restituidos de manera pronta y eficaz.",  
    },
    {
        area1Titulo: "DERECHO AMBIENTAL        ",
        area1Item1Titulo: "¿Conoces de algún daño al medio ambiente provocado por actividades de extracción de recursos no renovables?",
        area1Item1subTitulo: "Contáctanos. OSAP ABOGADOS LITIGANTES, en fiel apego a sus principios institucionales pone al servicio de la comunidad su equipo de profesionales a favor de los grupos más desfavorecidos; en este caso, la naturaleza y el medio ambiente en general como sujetos de derechos dentro de nuestro ordenamiento jurídico. En este sentido, si conoces un caso de contaminación al medio ambiente o daño a la naturaleza, nosotros contamos con un equipo apto para velar por la satisfactoria restitución de los derechos del medioambiente y a la par, la respectiva sanción para los responsables del siniestro.",
        area1Item2Titulo: "¿Vives en una zona aledaña a una industria y ésta no cumple con las respectivas medidas de cuidado ambiental?",
        area1Item2subTitulo: "Podemos ayudarte. Una de las responsabilidades del Estado ecuatoriano es poner en marcha políticas públicas que velen porque en nuestro territorio impere una ambiente sano, diverso y sostenible; así, las industrias que operan dentro de nuestro país se ven obligadas a cumplir con las respectivas medidas de cuidado ambiental. Si conoces de alguna industria que no cumple con dichos lineamientos, nuestro equipo de abogados puede ayudarte a plantear una demanda que vele por tus derechos y por los de la ciudadanía en general, recuerda que los altos índices de contaminación del ambiente han traído consigo el incremento de personas con enfermedades catastróficas como el cáncer.",  
    },
    {
        area1Titulo: "DERECHO LABORAL        ",
        area1Item1Titulo: "¿Requieres contratar personal y necesitas redactar un contrato de trabajo que se ajuste a tus necesidades?",
        area1Item1subTitulo: "Recuerda que el empleador deberá registrar la información de las personas trabajadoras activas a su cargo, en la plataforma informática habilitada en la página web institucional del Ministerio del Trabajo, debiendo realizar el registro del personal a su cargo hasta treinta (30) días término posteriores al ingreso de los mismos. Las modalidades de contratos vigentes más utilizadas son: contrato por obra o servicio determinado dentro del giro del negocio, contrato sector productivo, contrato agrícola, contrato sector turístico, contrato indefinido y contrato de jornada parcial permanente. Nosotros te ayudamos en la asesoría legal contractual que requiere tu empresa para precautelar que se cumpla con la normativa contenida en la Ley Orgánica del Servicio Público, su Reglamento General, Código de Trabajo, acuerdos ministeriales emitidos por el Ministerio del Trabajo, etc.",
        area1Item2Titulo: "¿Te despidieron injustamente?",
        area1Item2subTitulo: "En OSAP ABOGADOS LITIGANTES, procederemos a revisar la notificación realizada por el empleador del despido realizado y solicitaremos las indemnizaciones de ley que más favorezca al trabajador.",  
    },
    {
        area1Titulo: "DERECHO CIVIL        ",
        area1Item1Titulo: "¿Tienes una deuda por cobrar mediante facturas?",
        area1Item1subTitulo: "Si la factura por cobrar no excede los cincuenta salarios básicos unificados del trabajador en general, podemos iniciar un proceso monitorio a fin de reclamar judicialmente lo adeudado, acorde a lo establecido en el COGEP. Asesórate con nosotros.",
        area1Item2Titulo: "¿Quieres comprar un inmueble?",
        area1Item2subTitulo: "Asesórate previamente con nosotros. Los contratos de reservas de bienes inmuebles y/o promesas de compra venta pueden contemplar condiciones desfavorables para el comprador.",  
    },
    {
        area1Titulo: "DERECHO SANITARIO        ",
        area1Item1Titulo: "¿Eres propietario de un restaurante o cafetería?",
        area1Item1subTitulo: "La Agencia Nacional de Regulación, Control y Vigilancia Sanitaria (ARCSA) se encarga de controlar y vigilar las condiciones higiénico – sanitarias de los productos de uso y consumo humano, además de vigilar el cumplimiento de la normativa sanitaria en los establecimientos sujetos a control, entre ellos los restaurantes y cafeterías, cuidando de esta forma su calidad e inocuidad. En caso de que tengas una notificación o el Informe y el Acta de Inspección realizada a tu establecimiento, en la cual te notifican una posible sanción, contáctanos, en OSAP ABOGADOS LITIGANTES nos encargamos de tu defensa durante todas las etapas del proceso sancionatorio.",
        area1Item2Titulo: "¿Eres propietario de un establecimiento farmacéutico?",
        area1Item2subTitulo: "En OSAP ABOGADOS LITIGANTES nos encargamos de asesorarte con los trámites relacionados a la obtención de permiso de funcionamiento en la Agencia Nacional de Regulación, Control y Vigilancia Sanitaria (ARCSA).",  
    },
    {
        area1Titulo: "DERECHO MUNICIPAL        ",
        area1Item1Titulo: "Tienes un emprendimiento, pero ¿no cuentas con la Licencia Metropolitana Única para el Ejercicio de Actividades Económicas?",
        area1Item1subTitulo: "Podemos ayudarte. La LUAE está dirigida a personas naturales y jurídicas que realizan una actividad comercial a pequeña y gran escala en un establecimiento ubicado en el Distrito Metropolitano de Quito. En este sentido, como comerciante es importante que cuentes con toda la documentación necesaria que avale el funcionamiento reglamentario de tu negocio dentro de la ciudad de Quito, nuestro equipo de abogados te ayudará a cumplir con todos los requisitos y documentación necesaria para poner tu negocio en marcha acorde al ordenamiento jurídico vigente.",
        area1Item2Titulo: "¿Necesitas regularizar el estatus catastral de tu vivienda?",
        area1Item2subTitulo: "Tenemos la solución. Varios predios del Distrito Metropolitano de Quito han sido inintencionalmente mal generados, siendo obligatorio incurrir en su regularización a fin de evitar en un futuro cargas tributarias excedentes y perjudiciales para el administrado. En OSAP ABOGADOS LITIGANTES, contamos con un equipo de profesionales que te asesorará con suficiencia en el proceso de actualización de información en el sistema catastral.",  
    },
    {
        area1Titulo: "PROTECCIÓN ANIMAL        ",
        area1Item1Titulo: "En OSAP ABOGADOS LITIGANTES, tenemos elevada sensibilidad por el bienestar de los animales; en tal virtud, patrocinamos casos por maltrato animal. ",
        area1Item1subTitulo: "El Código Orgánico Integral Penal, tipifica ciertos actos como delitos: lesiones, abuso sexual o muerte de un animal puede conllevar una sentencia de prisión que puede llegar a los dos años. Y otros hechos son catalogados como contravenciones; por ejemplo, el abandono de animales de compañía tiene una sanción de trabajo comunitario de hasta 50 horas. Si eres testigo de actos perpetrados en contra de la vida e integridad de los animales de fauna urbana, contáctanos.",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },
    {
        area1Titulo: "INQUILINATO        ",
        area1Item1Titulo: "¿Tu inquilino no te paga el arriendo por varios meses?",
        area1Item1subTitulo: "Tenemos la solución. A raíz de la crisis económica que vive nuestro país, el desempleo y la escasa generación de ingresos ha provocado que muchas personas incumplan con sus obligaciones; entre ellas, adeudar por varios meses el canon de arrendamiento. Si te encuentras en una situación similar, nuestros abogados pueden ayudarte a solucionar tus problemas de inquilinato de la manera más pronta y eficaz posible, utilizando estrategias legales que se acoplen a tus necesidades particulares.",
        area1Item2Titulo: "¿Quieres dar por terminado el contrato de arrendamiento, pero el arrendador no te devuelve la garantía?",
        area1Item2subTitulo: "Ponte en contacto con nosotros. A menudo, existen conflictos de orden monetario cuando se dan por terminados los contratos de arrendamiento, en la mayoría de los casos el arrendador del bien inmueble desconoce la devolución de la garantía en compensación de la reparación de los supuestos daños ocasionados a su bien inmueble. Si te encuentras envuelto en un problema similar, nuestros abogados cuentan con la experticia necesaria para ayudarte a llegar a un acuerdo razonable con la contraparte, velando a cada momento por tus derechos e intereses.",  
    },
    {
        area1Titulo: "COMPLIANCE",
        area1Item1Titulo: "¿Te aseguras de que tus hijos entablen relaciones de amistad con personas que tengan un comportamiento acorde a los valores y principios que les has enseñado en tu hogar?",
        area1Item1subTitulo: "Lo mismo deberías hacer con tu empresa, no entables relaciones comerciales con proveedores sin antes conocer a profundidad su reputación. Sin darte cuenta tu empresa puede estar suscribiendo contratos con compañías que enfrentan procesos penales por varios delitos en los que luego te puedes ver involucrado. No permitas que la buena reputación de tu empresa se ponga en juego y adquiere un sistema de compliance que se encargue de que tu compañía tenga los mejores aliados comerciales.",
        area1Item2Titulo: "",
        area1Item2subTitulo: "",  
    },

]

export default areas